[project]
name = "editorchatbot-backend"
version = "0.1.0"
description = "Backend for Editor Chatbot"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "Flask==2.3.3",
    "Flask-Cors==4.0.0",
    "anthropic>=0.22.0",
    "python-dotenv==1.0.0"
]
